name: KICS Scan

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'user*/**/*.tf'

jobs:
  kics-scan:
    name: Run KICS Scanner
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      KICS_S3_BUCKET: kics-log-bucket  # replace with your actual bucket name

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Upload Flag
        id: set-upload-flag
        run: |
          if [ -n "${{ secrets.ACCESS_KEY }}" ] && [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "upload_enabled=true" >> $GITHUB_OUTPUT
          else
            echo "upload_enabled=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials (optional for S3 upload)
        if: steps.set-upload-flag.outputs.upload_enabled == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install KICS
        run: |
          curl -Lo kics https://github.com/Checkmarx/kics/releases/latest/download/kics-linux
          chmod +x kics
          sudo mv kics /usr/local/bin/

      - name: Run KICS on Terraform (user folders only)
        run: |
          mkdir -p kics-output
          for dir in user*/; do
            echo "Scanning $dir ..."
            kics scan -p "$dir" \
              -o kics-output \
              --output-name "kics-results-${dir%/}" \
              --report-formats json,html 
          done

      - name: Upload KICS Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kics-results
          path: kics-output/

      - name: Upload KICS Results to S3 (optional)
        if: steps.set-upload-flag.outputs.upload_enabled == 'true'
        run: |
          for file in kics-output/*; do
            echo "Uploading $file to S3..."
            aws s3 cp "$file" s3://$KICS_S3_BUCKET/kics-results/
          done
